Accessibility Evaluation
CobbyElsonfx/Portfolio-Website pull request #32
Opened 2023-06-13 21:13 UTC by CobbyElsonfx

Accessibility evaluation : 
- Page titles -    [https://github.com/CobbyElsonfx/Portfolio-Website/blob/b80b8d0de7fd5e0886b8d0f250306a174c0ec59e/index.html#L7](url)

-  Image text alternatives - [https://github.com/CobbyElsonfx/Portfolio-Website/blob/b80b8d0de7fd5e0886b8d0f250306a174c0ec59e/index.html#L52](url)
- Text headings. - no issues found
- Color contrast - no  issues found
- Resize - no issues found
- Interaction -  [https://github.com/CobbyElsonfx/Portfolio-Website/blob/b80b8d0de7fd5e0886b8d0f250306a174c0ec59e/index.html#L502](url)

- Moving content  - no issues found
- Multimedia  -  no issues found
- Basic structure of the page  - no issues found

2023-06-13 21:27 UTC, Ofarouq310 reviewed
Hi @CobbyElsonfx, ✋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![giphy](https://github.com/santitoot/finish-mobile-version/assets/102612396/3bea5f92-d775-4599-9dad-4670789be159)

## 🔴 Invalid Code Review Request

- Kindly note that for this pair programming activity and as per requirements, each one of you has to contribute together in your repositories.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-13 21:41 UTC, SnakyMz commented
I assure that we pair programmed this project. I do accept that we made small error, we forgot to add me as collaborator and we apolise for it with atmost sincerity. But I assure you, that we did this project together as per pair programming rules. Please review our request. Thank you

2023-06-13 21:47 UTC, Ofarouq310 commented
Hello @SnakyMz, kindly ask for another review from the dashboard and one of the reviewers will consider if your request can be validated. Try to make your peer commit even a little detail or something to satisfy the pair programming condition. 
I hope this helps.

2023-06-13 21:49 UTC, SnakyMz commented
> Hello @SnakyMz, kindly ask for another review from the dashboard and one of the reviewers will consider if your request can be validated. Try to make your peer commit even a little detail or something to satisfy the pair programming condition. I hope this helps.

Thank you very much, will do as suggested.

2023-06-14 01:43 UTC, Cabraham1 reviewed
# INVALID ❌ 

Hi @CobbyElsonfx and @SnakyMz  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😓

## Invalid Code Review Request ❌

- [x] Unfortunately, you have submitted a project that is not professional and does not includes all the headers/sections present in [readme template](https://github.com/microverseinc/readme-template)📖
- [ ] Note that the placeholders in README file that are meant to guide you on the contents of each of the sections. They are not meant to instruct users on how to contribute to the code so please ensure that you remove them.
- [ ] Please ensure that you professionally document the README file to reflect the project 😄
- [ ] Also update the author section since this is a collaboration project

You can take a step back and read the [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more clarity 💡

_**Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready**_ 🤝🙏

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 03:11 UTC, CobbyElsonfx commented
> # INVALID ❌
> 
> Hi @CobbyElsonfx and @SnakyMz
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 😓
> ## Invalid Code Review Request ❌
> 
>     * [ ]  Unfortunately, you have submitted a project that is not professional and does not includes all the headers/sections present in [readme template](https://github.com/microverseinc/readme-template)📖
> 
>     * [ ]  Note that the placeholders in README file that are meant to guide you on the contents of each of the sections. They are not meant to instruct users on how to contribute to the code so please ensure that you remove them.
> 
>     * [ ]  Please ensure that you professionally document the README file to reflect the project 😄
> 
>     * [ ]  Also update the author section since this is a collaboration project
> 
> 
> You can take a step back and read the [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for more clarity 💡
> 
> _**Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready**_ 🤝🙏
> 
> Cheers and Happy coding!👏👨‍💻💻
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 03:23 UTC, CobbyElsonfx commented
@Cabraham1  can you please provide a clear feedback on the first comment, I dont understand what you meant by 
-Unfortunately, you have submitted a project that is not professional and does not includes all the headers/sections present in [readme template](https://github.com/microverseinc/readme-template)📖

Are you implying we should  remove the "Getting started section of the readme "

- Note that the placeholders in README file that are meant to guide you on the contents of each of the sections. They are not meant to instruct users on how to contribute to the code so please ensure that you remove them.

2023-06-14 04:32 UTC, Cabraham1 commented
@CobbyElsonfx nice to hear from you.
On your author section it appears to show just one person which is not supposed to be since it's a collaboration between you and your partner. Your partner is supposed to add this details as second author on the readme

2023-06-15 11:49 UTC, wayungi requested changes
Hi <STUDENT_MENTION>, 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] Descriptive PR body ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Your portfolio title is very general. I suggest you change it to **Cobby's Portfolio**. A general title does not differentiate a page from others and is not very helpful 👍🏾 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 11:49 UTC, wayungi commented on index.html
> +                <h1 class="intro">About Myself</h1>
- [ ] You should only have one `h1` per page. A page can only have one main heading and the rest are sub headings. 
![h](https://github.com/CobbyElsonfx/Portfolio-Website/assets/99656687/a04b92b5-2aad-42e8-b270-e355cc228a4c)

2023-06-15 11:49 UTC, wayungi commented on index.html
> +          <li>Contact</li>
- [ ] These links have failed the accessiblitily test. That is because you have not labelled them as links. Please add the anchor tag to them. 👍🏾

2023-06-15 17:44 UTC, binhussen approved these changes
Hi @CobbyElsonfx , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- Applied Accesiblity✔️
- Well-structured Code ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 18:14 UTC, merged